audit_header: false
title: Dallas - Fort Worth Real Estate Video Blog with Brian and Tisha White
description: Our mission at BlueFuse Group is to be your best resource for Dallas - Fort Worth real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The BlueFuse Group, your professional Dallas - Fort Worth Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: true
custom_links_new_tab:
  - title: Home Valuation
    url: https://www.amazinghomesindfw.com/sell.php
  - title: Home Search
    url: https://www.amazinghomesindfw.com/index.php?rtype=


client:
  name: Brian and Tisha White
  title:
  license_number:
  about_markdown: |
    Founded in 2014, we are built around making your Real Estate experience AWESOME!

    BlueFuse was started by Tisha and Brian White to build a family business, serve our community and keep Brian closer to our 3 amazing boys. Brian spent 20 years in Fortune 50 companies leading teams, providing exceptional customer service and negotiating with some of the toughest businesses in the world. Tisha is simply brilliant in all things Real Estate. She has photographic recall of floor plans, builders and design. Plus, she’s an incredible connector.

    Why are we called BLUEFUSE?

    We’re BLUE because we’re blessed with those Amazing Boys and it’s our family’s favorite color for clothes, decor, you name it! FUSE means to join or blend. We FUSED our skills to provide YOU an EXCEPTIONAL Real Estate Experience.

    Now, we’re a growing team with outstanding, caring agents and staff, focused on building client Wealth whether you're buying, selling or investing in Real Estate.

    At BlueFuse, we make Real Estate Easy for YOU. Isn’t That a Bright Idea?
  brand: BlueFuse Group
  brokerage: eXp Realty
  market: Dallas - Fort Worth
  address: 2300 Highland Village Rd Suite 120<br>Highland Village, TX 75077
  phone: 817-752-9126
  phone_type:
  phone2:
  phone2_type:
  email: brian@bluefuserealty.com
  email2: tisha@bluefuserealty.com
  url: https://www.amazinghomesindfw.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.amazinghomesindfw.com/sell.php
  second_CTA_text: Home Search
  second_CTA_URL: https://www.amazinghomesindfw.com/index.php?rtype=

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Dallas - Fort Worth Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.amazinghomesindfw.com/sell.php

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Dallas - Fort Worth Home?"
    CTA_text2: "Search the entire MLS for your Dallas - Fort Worth home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.amazinghomesindfw.com/index.php?rtype=

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/BlueFuseRealty/
  linkedin_url: https://www.linkedin.com/in/bluefuserealty/
  youtube_url: https://www.youtube.com/channel/UCS7oKlYH-A6qYJ9PgPd4Wbg
  twitter_url: https://twitter.com/bluefuserealty
  instagram_url: https://www.instagram.com/bluefuserealty/
  pinterest_url: https://www.pinterest.com/bluefuserealty/
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: https://itunes.apple.com/us/podcast/dallas-fort-worth-real-estate-podcast-brian-tisha-white/id1450549266?mt=2

podcast:
  title: 'Dallas - Fort Worth Real Estate Podcast with Brian and Tisha White'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Dallas - Fort Worth Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from BlueFuse Group - your professional Dallas - Fort Worth Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Dallas - Fort Worth, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Brian and Tisha White'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo1.png
  logo_width_number: 40
  hero_text: Dallas - Fort Worth Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background1.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#2769e5'
  theme_color: '#123b4f'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
